username_login = "//input[@id='user-name']"  
password_login= "//input[@id='password']"    
Button_login =   "//input[@id='login-button']"
container="//body/div[@id='root']/div[@id='page_wrapper']/div[@id='contents_wrapper']/div[@id='header_container']/div[2]/div[1]/span[1]/select[1]"
Button1 =   "//button[@id='add-to-cart-sauce-labs-onesie']" 
Link =   "//a[@class='shopping_cart_link']" 
Button2 =  "//button[@id='checkout']  "
firstname="//input[@id='first-name']"  
lastname=   "//input[@id='last-name']"    
postalcode=  "//input[@id='postal-code']" 
button3="//input[@id='continue']"
element="//button[@id='finish']"